#!/bin/bash

. ../scripts/functions.sh

### path tweak for importing debian libraries
debian_lib_fixup

##byobu install
debian_import byobu bookworm all main

mkdir "$TARGET_DIR/boot/" 2>/dev/null

##install the current user's ssh key as a starting point for authentication
install_ssh_key

##tweaks for msmtp compatibility
mail_setup

##pull in initscripts to make rsyncd work
rsyncd_setup

##should be sufficiently version aware at this point
micro_evtd_install

##adjustments to make dcron work more or less how one would expect cron to behave
cron_setup

##really just custom stuff at this point
libmicon_install

###check if installed I imagine, ends up more or less noop for systemd, but that is also fine?
mdadm_setup

##any mainline vs oot concern?
r8152_config

##zfs init stuff for non systemd?
zfs_setup

##getty setup/fix
getty_setup

##network stuff, systemd-networkd in particular. hosts localhost?
network_setup

##move to hook for custom script with example?
cp ~/buildroot_keep/.msmtprc "$TARGET_DIR/root/"
cat ~/buildroot_keep/authorized_keys >> "$TARGET_DIR/root/.ssh/authorized_keys"
cp ~/buildroot_keep/smb.conf "$TARGET_DIR/etc/samba/"
cp ~/buildroot_keep/saveconfig.json "$TARGET_DIR/etc/target/"
cp ../custom/first_boot_test.sh "$TARGET_DIR/usr/bin"

zedrc="$TARGET_DIR/etc/zfs/zed.d/zed.rc"
[ -f "$zedrc" ] && grep -qve "^ZED_EMAIL_ADDR" "$zedrc" && cat ~/buildroot_keep/zed-config >> "$zedrc"

cp -v ~/buildroot_keep/root "$TARGET_DIR$crondir/crontabs/"
for x in exports mdadm.conf rsyncd.conf rsyncd.secrets aliases
do
  cp "$HOME/buildroot_keep/$x" "$TARGET_DIR/etc/$x"
done

mkdir "$TARGET_DIR/mnt/array" 2>/dev/null

exit 0
